### ISSUE TITLE
标签左对齐怎么处理，点击更多能否展开

### ISSUE THREAD

**Issue by xuhuan** [kingideayou/TagCloudView#3]
如题，目前单行模式下在1080p的设备上标签居中偏左一点排列，在480p设备上偏右排列。
多行模式下正常。

**Comment by kingideayou** [comment]
感谢反馈。
左对齐是什么意思，没太理解，最好可以截个图...
已添加 TagCloudView.singleLine(boolean) 方法，可以动态设置单行或多行显示。暂未上传到 JCenter

**Comment by xuhuan** [comment]
就像这个issue的网页排版一样，我们现在打出来的字都是从左往右排列过去。排列贴着最左边开始往后面排。
现在单行模式下多个标签并不是从左边开始排的，而是如一开始说的那样子。
换到android里是

```
android:gravity="left"
```

**Comment by kingideayou** [comment]
单行模式的效果跟[效果图](https://raw.githubusercontent.com/kingideayou/TagCloudView/master/imgs/tagCloudView_1.png)不一样吗？这个效果图就是左对齐的啊...

**Comment by xuhuan** [comment]
不一样，参数设置如下

```
<me.next.tagview.TagCloudView
            android:id="@+id/tag_cloud_view_4"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:tcvBackground="@drawable/background_tag_selector"
            app:tcvTextColor="#42A5F5"
            app:tcvShowRightImg="false"
            app:tcvSingleLine="true"
            app:tcvTextSize="10px"
            />
```

其他不变，就下面的改成多行的就正常了。

```
app:tcvSingleLine="false"
```
